# 毎回パス書くのだるいから、これでええやろ、
path = ..\Code\main.go ..\Code\file.go ..\Code\console.go ..\Code\math.go ..\Code\function.go

b:
	go build -o a.exe $(path)

r:
	go run $(path)

tag:
	git push origin --tags

log:
	git fsck
